spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/auto-ria?createIfNotExist=true
    username: root
    password: root
jwt:
  signingKey: super_long_secret_key_that_nobody_knows